### ISSUE TITLE
Doesn't seem to run

### ISSUE THREAD

**Issue by katieorenstein** [Knewton/RandomLunch#1]
I've set up my google doc with a few emails and teams to test this out, and pasted the script into the google apps script, but when I hit run, nothing happens. I don't get an error, nothing shows up in my log, and no one gets a calendar invite. 

When I click run, it says "Running myFunction" for a quick second and then it goes away, and I get no feedback that anything happened. I love this idea and really want to use this at work, but am I doing something wrong?

**Comment by trevorsummerssmith** [comment]
@katieorenstein Ack. I'm excited you're excited about this! I am happy to help offline to debug this. If we come up with any needed changes to the code I'll submit a PR in the ticket. Once we figure out what is going on please feel free to close the ticket here.

**Comment by katieorenstein** [comment]
Everything's working now! Thanks @trevorsummerssmith! 

If anyone else has this issue in the future: make sure to erase the code google puts in a new script doc (myFunction) and paste this code in a clean doc. Then make sure when you run it, you are running "main".
